[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_STORYBLOK_ACCESS_TOKEN = "75Os0ynnS4rM27uvkM8EoQtt"
  NEXT_PUBLIC_STORYBLOK_PREVIEW_TOKEN = "eHn8yhaa2KyhmUlzKb9PHgtt"
  STORYBLOK_SPACE_ID = "287766077619539"
  STORYBLOK_REGION = "eu-central-1"
  NODE_ENV = "production"
